
#define     PROC_FLIP 				4
#define     PROC_MIRROR				5
#define     PROC_NEGATIVE				6
#define     PROC_GRAYSCALE				7
#define     PROC_DITHER				8
#define     PROC_THRESHOLD				9
#define     PROC_COLORIZE				10
#define     PROC_LIGHTEN				11
#define     PROC_DARKEN				12
#define     PROC_BRIGHTNESSCONTRASTCOLOR				13
#define     PROC_CONTRAST				14
#define     PROC_LESSCONTRAST				15
#define     PROC_DILATE				16
#define     PROC_ERODE				17
#define     PROC_CONTOUR				18
#define     PROC_ADDNOISE				19
#define     PROC_JITTER				20
//define		PROC_EDGE				121
#define     PROC_CIRCLETRANSFORM_CYLINDER				21
#define     PROC_CIRCLETRANSFORM_PINCH				22
#define     PROC_CIRCLETRANSFORM_PUNCH				23
#define     PROC_CIRCLETRANSFORM_SWIRL				24
#define     PROC_CIRCLETRANSFORM_BATHROOM				25
#define     PROC_EMBOSS				26
#define     PROC_BLUR				27
#define     PROC_GAUSSIAN3X3				28
#define     PROC_GAUSSIAN5X5				29
#define     PROC_SOFTEN				30
#define     PROC_SHARPEN				31
#define     PROC_EDGE				32
#define     PROC_MEDIAN				33
#define     PROC_GAMMA				34
#define     PROC_HISTOGRAM_LOG				35
#define     PROC_HISTOGRAM_ROOT				36
#define     PROC_HISTOGRAM_EQUALIZE				37
#define     PROC_HISTOGRAM_NORMALIZE				38
#define     PROC_HISTOGRAM_STRETCH				39
#define     PROC_HISTOGRAM_STRETCH1				40
#define     PROC_HISTOGRAM_STRETCH2				41
#define     PROC_SKEW				42
#define     PROC_ROTATE				43
#define     PROC_ROTATEL				44
#define     PROC_ROTATER				45
#define     PROC_RESAMPLE				46
#define     PROC_INCREASEBPP				47
#define     PROC_DECREASEBPP				48
#define		PROC_LIGHT				49
#define		PROC_REPAIR				50
#define		PROC_TEMPLATE			51